# Generated by Django 5.2.3 on 2025-06-27 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='Main heading for this slide', max_length=255)),
                ('sub_heading', models.CharField(blank=True, help_text='Subheading for this slide', max_length=255, null=True)),
                ('tagline', models.TextField(blank=True, help_text='Short tagline for this slide', null=True)),
                ('image', models.ImageField(help_text='Background image for this slide', upload_to='hero_slides/')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for the slide image', max_length=255, null=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which slides appear')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this slide is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('source', models.CharField(default='Hero Form', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('url_path', models.CharField(help_text="e.g., '/', '/about', '/services'", max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Order in which links appear in navigation')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Navigation Links',
                'ordering': ['order', 'text'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Unique identifier for this content block (e.g., 'hero_main_heading', 'about_us_paragraph_1', 'hero_background_image_desktop', 'contact_us_phone', 'site_meta_title')", max_length=255, unique=True)),
                ('value', models.TextField(blank=True, help_text='The actual content: text or HTML. Optional if an Image File is uploaded.', null=True)),
                ('content_image', models.ImageField(blank=True, help_text="Upload an image file if 'Content type' is 'Image File'.", null=True, upload_to='website_content_images/')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('html', 'HTML'), ('image_file', 'Image File'), ('link', 'Link URL')], default='text', help_text='Type of content: Text, HTML, Image File, or Link URL.', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Website Content',
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_thumbnail', models.BooleanField(default=False, help_text='Set to True for the primary image displayed on service cards.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='my_app.service')),
            ],
            options={
                'verbose_name_plural': 'Service Images',
                'ordering': ['service', '-is_thumbnail', 'uploaded_at'],
            },
        ),
    ]
