# Generated by Django 5.2.3 on 2025-06-26 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='A descriptive title for the image (optional)', max_length=255, null=True)),
                ('image', models.ImageField(upload_to='site_images/')),
                ('alt_text', models.CharField(blank=True, help_text="Alt text for accessibility (e.g., 'Hero section background image')", max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Site Images',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('html', 'HTML'), ('image_url', 'Image URL'), ('image_object', 'Image Object'), ('link', 'Link URL')], default='text', help_text="Type of content stored in the 'value' field OR linked via 'image_object'.", max_length=50),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='value',
            field=models.TextField(blank=True, help_text='The actual content: text, HTML, or URL for non-image types. Optional if an Image Object is selected.', null=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='image_object',
            field=models.ForeignKey(blank=True, help_text="Link to a Site Image if 'Content type' is 'Image Object'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.siteimage'),
        ),
    ]
