# Generated by Django 5.2.3 on 2025-06-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'), # <--- THIS IS THE ONLY DEPENDENCY NOW
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitecontent',
            name='image_object',
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='content_image',
            field=models.ImageField(blank=True, help_text="Upload an image file if 'Content type' is 'Image File'.", null=True, upload_to='website_content_images/'),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('html', 'HTML'), ('image_file', 'Image File'), ('link', 'Link URL')], default='text', help_text='Type of content: Text, HTML, Image File, or Link URL.', max_length=50),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='value',
            field=models.TextField(blank=True, help_text='The actual content: text or HTML. Optional if an Image File is uploaded.', null=True),
        ),
        migrations.DeleteModel(
            name='SiteImage',
        ),
    ]